---

name: CI
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    -
      cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        with:
          version: latest
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: type-check
        run: pnpm type-check
