---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    -
      cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
