---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    -
      cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
